name: POC Bedrock Log Analysis

on:
  push:
    branches: [ main ]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar SAM CLI
        run: pip install aws-sam-cli==1.97.0

      - name: Build SAM
        run: sam build

      - name: Deploy SAM
        run: |
          sam deploy \
          --stack-name bedrock-log-stack \
          --no-confirm-changeset \
          --capabilities CAPABILITY_IAM \
          --region ${{ secrets.AWS_REGION }} \
          --s3-bucket bedrock-log-deploy

      - name: Invocar Lambda (teste)
        run: |
          echo '{"logs":"ERROR: Timeout at step 3"}' > payload.json
          aws lambda invoke \
            --function-name bedrock-log-analyzer \
            --cli-binary-format raw-in-base64-out \
            --payload file://payload.json \
            response.json
          cat response.json

      - name: Notificar conclusão
        run: |
         echo "✅ Execução concluída com sucesso!"
         echo "LogWise: 🚨 Alerta de Anomalia Detectada - Loop infinito de logs no serviço "payment-processor" iniciado em 23/11 às 14:32"
